# -*- coding: utf-8 -*-
"""Waze_GDA _Project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y30gaW_wjiaWT1wIW6hNYFxUIhHafKCx
"""

# Import packages for data manipulation
import pandas as pd
import numpy as np

# Import packages for data visualization
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('waze_dataset.csv')

# The number of occurrence of a user opening the app during the month

total_occurrences = df['sessions'].sum()
total_occurrences

plt.figure(figsize=(10, 5))
sns.boxplot(data= df , y= df['sessions'] )
plt.xlabel('Sessions')
plt.ylabel('Count')
plt.show()

median_sessions = df['sessions'].median()

plt.figure(figsize=(10, 5))
sns.histplot(data= df , x= df['sessions'] )
plt.axvline(median_sessions, color='red', linestyle='dashed', linewidth=2)
plt.text(median_sessions + 0.5, plt.gca().get_ylim()[1] * 0.9 , f'Median: {median_sessions}', color='red')
plt.xlabel('Sessions')
plt.ylabel('Count')
plt.show()

df.isnull().sum()

import seaborn as sns
sns.heatmap(df.isnull(), cbar=False)

# drives
# An occurrence of driving at least 1 km during the month

df_driving = df[df['drives'] >= 1]

plt.figure(figsize=(10, 5))
sns.boxplot(data= df_driving , y= df_driving['drives'] )
plt.xlabel('Drives')
plt.ylabel('Count')
plt.show()

median_drives = df_driving['drives'].median()


plt.figure(figsize=(10, 5))
sns.histplot(data= df_driving , x= df_driving['drives'] )
plt.axvline(median_drives, color='red', linestyle='dashed', linewidth=2)
plt.text(median_drives + 0.5, plt.gca().get_ylim()[1] * 0.9, f'Median: {median_drives}', color='red')
plt.xlabel('Drives')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(data = df , y = df['total_sessions'])
plt.xlabel('Total Sessions')
plt.ylabel('Count')
plt.show()

median_total_sessions = df['total_sessions'].median()

plt.figure(figsize=(10, 5))
sns.histplot(data = df , x = df['total_sessions'])
plt.axvline(median_total_sessions, color='red', linestyle='dashed', linewidth=2)
plt.text(median_total_sessions + 0.5, plt.gca().get_ylim()[1] * 0.9, f'Median: {median_total_sessions :.2f}', color='red')
plt.xlabel('Total Sessions')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(data = df , y = df['n_days_after_onboarding'])
plt.xlabel('N Days After Onboarding')
plt.ylabel('Count')
plt.show()

median_n_days_after_onboarding = df['n_days_after_onboarding'].median()

plt.figure(figsize=(10, 5))
sns.histplot(data = df , x = df['n_days_after_onboarding'])
plt.axvline(median_sessions, color='red', linestyle='dashed', linewidth=2)
plt.text(median_n_days_after_onboarding + 0.3, plt.gca().get_ylim()[1] * 0.9,
         f'Median: {median_n_days_after_onboarding}', color='red')
plt.xlabel('N Days After Onboarding')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(data = df , y = df['driven_km_drives'])
plt.xlabel('Driven KM Drives')
plt.ylabel('Count')
plt.show()

media_deriven_km_drives = df['driven_km_drives'].median()

plt.figure(figsize=(10, 5))
sns.histplot(data = df , x = df['driven_km_drives'])
plt.axvline(media_deriven_km_drives, color='red', linestyle='dashed', linewidth=2)
plt.text(media_deriven_km_drives + 0.5, plt.gca().get_ylim()[1] * 0.9
         , f'Median: {media_deriven_km_drives:.2f}', color='red')
plt.xlabel('Driven KM Drives')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(data = df , y = df['duration_minutes_drives'])
plt.xlabel('Duration Minutes Drives')
plt.ylabel('Count')
plt.show()

median_duration_minutes_drives = df['duration_minutes_drives'].median()

plt.figure(figsize=(10, 5))
sns.histplot(data = df , x = df['duration_minutes_drives'])
plt.axvline(median_duration_minutes_drives, color='red', linestyle='dashed', linewidth=2)
plt.text(median_duration_minutes_drives + 0.5, plt.gca().get_ylim()[1] * 0.9
         ,f'Median: {median_duration_minutes_drives:.2f}', color='red')
plt.xlabel('Duration Minutes Drives')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(data = df , y = df['activity_days'])
plt.xlabel('Activity Days')
plt.ylabel('Count')
plt.show()

median_activity_days = df['activity_days'].median()

plt.figure(figsize=(10, 5))
sns.histplot(data = df , x = df['activity_days'])
plt.axvline(median_activity_days, color='red', linestyle='dashed', linewidth=2)
plt.text(median_activity_days + 0.5, plt.gca().get_ylim()[1] * 0.9
         , f'Median: {median_activity_days}', color='red')
plt.xlabel('Activity Days')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(data = df_driving , y = df['driving_days'])
plt.xlabel('Driving Days')
plt.ylabel('Count')
plt.show()

median_deriving_days = df_driving['driving_days'].median()

plt.figure(figsize=(10, 5))
sns.histplot(data = df_driving , x = df_driving['driving_days'])
plt.axvline(median_deriving_days, color='red', linestyle='dashed', linewidth=2)
plt.text(median_deriving_days + 0.5, plt.gca().get_ylim()[1] * 0.9, f'Median: {median_deriving_days}', color='red')
plt.xlabel('Driving Days')
plt.ylabel('Count')
plt.show()



plt.figure(figsize=(10, 5))
plt.pie(df['device'].value_counts(), labels=df['device'].value_counts().index, autopct='%1.1f%%')
plt.title('Device Distribution')
plt.show()

plt.figure(figsize=(10, 5))
plt.pie(df['label'].value_counts(), labels=df['label'].value_counts().index, autopct='%1.1f%%')
plt.title('Label Distribution')
plt.show()

plt.figure(figsize=(12, 6))
# Prepare data for plotting by selecting the two columns
data = df[['driving_days', 'activity_days']]

# Plot a histogram for both columns
sns.histplot(data=data, multiple='dodge', bins=range(0, 32))

plt.title('Driving Days vs. Activity Days')
plt.xlabel('Days')
plt.ylabel('Count')
plt.xticks(range(0, 32, 2))
plt.show()

max_driving_days = df['driving_days'].max()
max_activity_days = df['activity_days'].max()

print(f'Maximum driving days: {max_driving_days}')
print(f'Maximum activity days: {max_activity_days}')

plt.figure(figsize=(12, 6))
plt.scatter(df['driving_days'], df['activity_days'])
plt.plot([0, 32], [0, 32], color='red', linestyle='--')
plt.title('Driving Days vs. Activity Days')
plt.xlabel('Driving Days')
plt.ylabel('Activity Days')
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='device', hue='label', multiple='dodge', shrink=0.8)
plt.title('Retention by Device')
plt.xlabel('Device')
plt.ylabel('Count')
plt.show()

# Create km_per_driving_day column
df['km_per_driving_day'] = df['driven_km_drives'] / df['driving_days']

# Get descriptive statistics by label (retained vs churned)
print(df.groupby('label')['km_per_driving_day'].describe())

# Convert infinite values to zero
df['km_per_driving_day'] = df['km_per_driving_day'].replace([np.inf, -np.inf], 0)

# Confirm the change with descriptive statistics
print(df.groupby('label')['km_per_driving_day'].describe())

plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='km_per_driving_day', hue='label', multiple='dodge', bins=20, shrink=0.8)
plt.title('Kilometers per Driving Day by Label')
plt.xlabel('KM per Driving Day')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(12, 6))
sns.histplot(data=df[df['km_per_driving_day'] <= 1200], x='km_per_driving_day', hue='label', multiple='fill', bins=20)
plt.title('Percentage of Retained vs Churned Users by KM per Driving Day')
plt.xlabel('KM per Driving Day')
plt.ylabel('Percent')
plt.show()

plt.figure(figsize=(12, 6))
sns.histplot(data=df, x='driving_days' , hue='label', multiple='fill' , bins=range(0, 32))
plt.title('Churn Rate per Number of Driving Days')
plt.xlabel('Driving Days')
plt.ylabel('Percent')
plt.xticks(range(0, 32, 2))
plt.show()

df['percent_sessions_in_last_month'] = round((df['sessions'] / df['total_sessions']) * 100 ,2)
display(df[['sessions', 'total_sessions', 'percent_sessions_in_last_month']].head())

df['percent_sessions_in_last_month'].median()

plt.figure(figsize=(10,5))
sns.histplot(data=df, x='percent_sessions_in_last_month', hue='label', multiple='dodge')
plt.title('Retention by Percent Sessions in Last Month')
plt.xlabel('Percent Sessions in Last Month')
plt.ylabel('Count')
plt.show()

df['n_days_after_onboarding'].median()

plt.figure(figsize=(10,5))
sns.histplot(data= df , x= df['n_days_after_onboarding'])
plt.xlabel('N Days After Onboarding')
plt.ylabel('Count')
plt.show()

def cal_95th_percentile (df_name, col_name):
    nth_percentile = df_name[col_name].quantile(0.95)
    return nth_percentile

data_percent95 = ['sessions' ,'drives' , 'total_sessions' , 'driven_km_drives'
                  ,'duration_minutes_drives']

for data in data_percent95:
  print(f'The 95th percentile of {data} is {cal_95th_percentile(df , data) : .2f}')